### ISSUE TITLE
Generic Input

### ISSUE THREAD

**Issue by adamthrash** [IGBB/PAST#43]
## Problem

PAST currently accepts input formatted as [TASSEL](https://www.maizegenetics.net/tassel) formats it, but several users have requested that PAST also accept more generic input.

## Proposed Solution

PAST should be fairly agnostic to the type of user input. To that end, PAST will accept three types of input.

* TASSEL output (two files - a association file with one line per marker and an effects file with two lines per marker)
* single-file input (a single file with one line per marker that also includes the effects data)
* two-file input (two files as TASSEL, but with one line per marker in the effects file)

The `load_GWAS_data` function should become a wrapper that accepts input files, input column names, and type of input. Based on the type of input, `load_GWAS_data` should pass files and column names to one of three functions - `load_single_generic`, `load_two_generic`, or `load_TASSEL` (the current `load_GWAS_data`).
 
### PAST Shiny

In PAST Shiny, a dropdown menu should allow the user to select a type, and based on the value of the user's selection, file input menu items should be displayed or hidden.

## TO-DO

- [X] migrate `load_GWAS_data` to `load_TASSEL`
- [X] create `load_GWAS_data` and test with TASSEL data
- [x] create `load_single_generic`
- [x] create `load_two_generic`
- [x] create test datasets for `load_single_generic` and `load_two_generic`
- [x] test  `load_single_generic` and `load_two_generic`
- [ ] update PAST Shiny
- [ ] update PAST Shiny MaizeGDB

**Comment by adamthrash** [comment]
Closed due to rewriting PAST in Rust
